### PR TITLE
MULE-19456: Encode characters from RFC 3986 in HTTP Request Path (#506)

### PR DESCRIPTION
**Pull request by mbuchwald**

### CODE REVIEW

**Review by eze210 — APPROVED** [review]

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Pull request merged**
